// Generated by `pnpm openapi` from apps/api/openapi.json. Do not edit.
// Source of truth: the zod contracts and routes in apps/api and packages/schema.

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness and readiness in one answer
         * @description 200 when the database answers and committed migrations are applied; 503 with the same body when either fails.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every dependency answers. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description Database unreachable or migrations pending. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin a bank login
         * @description Opened in the system browser by the app. Redirects to the identification broker's bank chooser; the person comes back through /auth/callback and the app receives a one-time code by deep link.
         */
        get: {
            parameters: {
                query: {
                    /** @description The app that will receive the one-time code by deep link. */
                    platform: "ios" | "android";
                    /** @description The language of the bank chooser (ui_locales); defaults to the request's. */
                    locale?: "fi" | "sv" | "en";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to the broker. */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No identification broker is configured. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The broker's return
         * @description The registered redirect URI. Exchanges the code with the broker, derives the identity, applies the re-registration rule and redirects to the app's deep link with a one-time code. Never called by the app itself.
         */
        get: {
            parameters: {
                query: {
                    code?: string;
                    state: string;
                    error?: string;
                    error_description?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to kuutti://auth?code=… on success, or to kuutti://auth?error=<code> (auth_state_mismatch, auth_cancelled, auth_under_18, auth_banned, auth_suspended, auth_cooldown with &until=<date>, auth_provider_error) so the app shows the refusal. */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange the one-time code for a session
         * @description Single use, within 60 seconds of the callback. Answers with this device's access and refresh tokens; the app keeps both in secure storage.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AuthExchangeRequest"];
                };
            };
            responses: {
                /** @description The device's session. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthExchangeResponse"];
                    };
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unknown, used or expired code (auth_code_used). */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the session's tokens
         * @description Presents the refresh token, receives a new pair; the old refresh token is retired. Presenting a retired token ends the device's session (session_revoked): sign in through the bank again.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AuthRefreshRequest"];
                };
            };
            responses: {
                /** @description The new pair. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionTokens"];
                    };
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Retired, revoked, expired or unknown refresh token (session_revoked). */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This device's session */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The caller's own session. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out this device */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The session is ended; both tokens stop working. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out every device
         * @description Recovery for a lost phone: every session of the account ends, including this one.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every session of the account is ended. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin a staff bank login
         * @description Opened by the moderation panel. The same bank login as the app's, marked as a staff attempt: it resolves to an identity with a moderator role and creates nothing. The browser returns to the panel with a one-time code in the URL fragment, or with error=admin_not_allowed.
         */
        get: {
            parameters: {
                query?: {
                    /** @description The language of the bank chooser; defaults to the request's. */
                    locale?: "fi" | "sv" | "en";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to the broker. */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No identification broker is configured. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a staff one-time code for an admin session
         * @description Single use, within 60 seconds. Eight hours, no refresh; sign in again afterwards.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AdminAuthExchangeRequest"];
                };
            };
            responses: {
                /** @description The admin session. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminSession"];
                    };
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unknown, used or expired code (auth_code_used). */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description admin_not_allowed: the role was taken away meanwhile. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This admin session */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The role and when the session ends. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminWhoAmI"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End this admin session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The session is ended. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete this account
         * @description Erasure per TD-7: every session, login attempt, photo (with its objects unless another account shares them), review row and fetch log entry goes; the account row stays as an anonymised tombstone and the identity keeps a deletion count and a 30-day cooldown before a new account. The audit log is untouched. The body confirms; the app asks first.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccountDeletionRequest"];
                };
            };
            responses: {
                /** @description Erased. Every token of this account has stopped working. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation failed (confirm missing). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No live account: a second deletion that passed the session guard before the first committed (not_found). */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything Kuutti holds about this account
         * @description One JSON document: the account, the identity's dates and login level, the devices signed in, the photos with fifteen-minute URLs and their moderation outcome, and the person's own fetch log. Nothing about anyone else.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The export. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountExport"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's photos
         * @description In the owner's order, with the blurhash to paint before the bytes arrive.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The caller's own photos. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PhotoList"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Upload a photo
         * @description Multipart with one part named photo (JPEG, PNG or WebP, at most 10 MB). The API validates, strips metadata, re-encodes into three WebP variants and keeps no original. The photo is pending until moderation; the owner sees it, nobody else.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": components["schemas"]["PhotoUploadRequest"];
                };
            };
            responses: {
                /** @description Stored, pending moderation. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Photo"];
                    };
                };
                /** @description Validation failed (no photo part, or not an accepted type). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description photo_limit: the account has max_photos photos already. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description payload_too_large: over 10 MB. */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description photo_unsupported: the bytes are not a JPEG, PNG or WebP. */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description photo_too_many_pixels or photo_invalid: refused before or by the decoder. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description media_busy with Retry-After: image processing is at capacity; or media_unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a photo */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["PhotoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Gone, along with its objects when nothing else shared them. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not a photo of this account. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set the order of the photos
         * @description Position 0 is the main photo. Every photo of the account exactly once.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PhotoOrderRequest"];
                };
            };
            responses: {
                /** @description The photos in the new order. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PhotoList"];
                    };
                };
                /** @description Validation failed, or photo_order_invalid. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}/{variant}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A signed URL for one variant
         * @description Valid for fifteen minutes. Every issuance is logged against the caller and counted against the day's budget for the variant (matching_config.photo_fetches_per_day; the day rolls at midnight in Finland). The app caches by photo id and variant, never by this URL, and asks for full only from the zoom screen. Another account's photo is served only from a card the caller was shown.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["PhotoId"];
                    /** @description thumb: 200×200 for lists. card: 800×1067 when a profile is opened. full: 1600 px long edge, requested only from the zoom screen. */
                    variant: components["schemas"]["PhotoVariant"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The URL and when it stops working. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PhotoUrlResponse"];
                    };
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not a photo this account may see: not its own, and not on a card it was shown. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description photo_budget_exceeded: the day's fetches of this variant are used up; Retry-After is the wait until the day rolls. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description media_unavailable: no object storage is configured here. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/photos/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Photos waiting for a person's decision
         * @description Oldest first, with what the automatic check saw: labels with confidences, faces, what was flagged.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The queue. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PhotoReviewQueue"];
                    };
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description admin_forbidden: the role does not allow this. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/photos/{id}/card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A signed URL for the card variant, for review
         * @description Any photo, any state. Every issuance is an audit_log row naming the member of staff.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["PhotoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The URL and when it stops working. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PhotoUrlResponse"];
                    };
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description admin_forbidden: the role does not allow this. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No such photo. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description media_unavailable: no object storage is configured here. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/photos/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve or reject a photo
         * @description approve makes the photo visible to others; reject hides it and tells the owner the reason in words. Only a queued photo takes a decision, once. Only a person rejects. Written to audit_log.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["PhotoId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PhotoDecisionRequest"];
                };
            };
            responses: {
                /** @description The photo's new state. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PhotoDecisionResponse"];
                    };
                };
                /** @description Validation failed (a rejection without a reason, for example). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description admin_forbidden: the role does not allow this. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No such photo. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description photo_not_queued: the photo is not waiting for a decision (already decided, or still being checked). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's profile and what it still needs
         * @description The profile as saved (null before the first save) and the completeness rule's verdict: what is missing before the profile can enter a round.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The profile. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfileResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /**
         * Save the caller's profile
         * @description The whole document every time: display name, a bio or a placeholder, the fields from the registry, up to three prompts, and the special-category consent version when a field needs it. Free text passes the plain-text rule: no e-mail, URL, phone number or social handle.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProfileUpdate"];
                };
            };
            responses: {
                /** @description Saved; the profile as stored, with its completeness. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfileResponse"];
                    };
                };
                /** @description Validation failed, or text_contact_details (a field carries an e-mail, URL, phone number or handle). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description consent_required: a politics or religion answer without the consent of the current wording (ADR-019); the detail names the fields and the current version. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No live account (erased meanwhile). */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description agreement_outdated: a consent version that is not the current wording's. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's own card, as others will see it
         * @description The card built the way a round builds it for someone else, with the age from the bank-verified year and month, the approved photos in order (bytes through GET /photos/{id}/{variant}) and what is still missing. Nothing is recorded: this is the owner looking at themselves.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The card, or null before the first save. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CardPreviewResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the caller has answered and what activation still waits for
         * @description Gender, pond, the two hard preferences, the consents given for the current wordings and the current versions. When nothing required is missing and the account is still registered, it becomes active here.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The status. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnboardingStatus"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/gender": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Declare the caller's gender
         * @description Self-declared, one of a closed list (rule 3); nothing from the bank informs it.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GenderUpdate"];
                };
            };
            responses: {
                /** @description Declared. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No live account (erased meanwhile). */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every consent the caller has given, and the current versions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The consents. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConsentsResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Record a consent for the current wording
         * @description The kind, the consent_version the person read and the language it was shown in. An old version is refused with agreement_outdated; the same consent twice is recorded once.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConsentRequest"];
                };
            };
            responses: {
                /** @description Recorded; the consents as stored. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConsentsResponse"];
                    };
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No live account (erased meanwhile). */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description agreement_outdated: the wording has a newer version. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description too_many_changes: the research opt-in was given and withdrawn more than the day allows. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consents/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Withdraw the research opt-in
         * @description The one consent a person withdraws; terms and privacy end with the account. The rows stay as the record of what was agreed and when.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Withdrawn; the consents as stored. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConsentsResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No live account (erased meanwhile). */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Where the caller stands at the pond gate
         * @description Between a finished profile and the first round (TD-10): on the pond's waitlist with a place, let in and waiting for enough people who match (how many more, in steps of `step`), or open. Counted nightly, and once when a person with a finished profile first asks.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The caller's gate. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GateResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The waitlist counter
         * @description Per pond: bank-verified people waiting, their split by self-declared gender, and how many are finishing their profile. A number is published only where at least k people stand behind it (k is in the answer), the split only when every cell is at least k, and a pond's numbers move only once at least k people have come or gone since they were last said. Counted once a day. No session needed.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every pond with what may be said of it. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WaitlistResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ponds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The ponds a person can choose
         * @description Every pond with both Finnish case forms (TD-17), parents first. Where matching happens (TD-10); the choice is one per account.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The ponds. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PondList"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/pond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Choose the caller's pond */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PondChoice"];
                };
            };
            responses: {
                /** @description Chosen. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation failed, or pond_unknown. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No live account (erased meanwhile). */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whom the caller seeks and the age window
         * @description The two hard filters of rule 7 as the person set them; null until onboarding sets them.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The preferences. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PreferencesResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /**
         * Set whom the caller seeks and the age window
         * @description Both at once: a non-empty set of genders and an age window within 18 and 99 with min at most max. Hard rows: the round builder never crosses them, in either direction.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PreferencesUpdate"];
                };
            };
            responses: {
                /** @description Saved; the preferences as stored. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PreferencesResponse"];
                    };
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No live account (erased meanwhile). */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /**
             * @description ok when the database answers and migrations are current; degraded otherwise.
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** @description APP_VERSION injected at build time. */
            version: string;
            /** @description Short git commit the build was made from. */
            commit: string;
            /** @description ISO 8601 build timestamp. */
            builtAt: string;
            /**
             * Format: uri
             * @description Where the source of the running service is published (AGPL-3.0 section 13), to be read with `commit`. A modified deployment points this at its own source.
             */
            source: string;
            /**
             * @description SELECT 1 answered within 500 ms.
             * @enum {string}
             */
            db: "ok" | "unreachable";
            /**
             * @description Committed migrations compared with the ones applied to this database.
             * @enum {string}
             */
            migrations: "current" | "pending";
        };
        ErrorResponse: {
            error: {
                /** @description Stable machine-readable code. */
                code: string;
                /** @description Short, generic, safe to show. */
                message: string;
                /** @description Matches the API log line. */
                requestId: string;
            };
        };
        AuthExchangeResponse: {
            /**
             * Format: uuid
             * @description This device's session; the app keeps it with the tokens.
             */
            sessionId: string;
            /** @description Bearer token; valid until accessExpiresAt. */
            accessToken: string;
            /** Format: date-time */
            accessExpiresAt: string;
            /** @description Single use: /auth/refresh answers with a new pair and retires this one. */
            refreshToken: string;
            /**
             * Format: date-time
             * @description After this the device logs in through the bank again.
             */
            refreshExpiresAt: string;
            /**
             * @description created: a fresh account (first login or after a cooldown); resumed: the live account.
             * @enum {string}
             */
            outcome: "created" | "resumed";
        };
        AuthExchangeRequest: {
            /** @description The one-time code the deep link carried. */
            code: string;
        };
        SessionTokens: {
            /**
             * Format: uuid
             * @description This device's session; the app keeps it with the tokens.
             */
            sessionId: string;
            /** @description Bearer token; valid until accessExpiresAt. */
            accessToken: string;
            /** Format: date-time */
            accessExpiresAt: string;
            /** @description Single use: /auth/refresh answers with a new pair and retires this one. */
            refreshToken: string;
            /**
             * Format: date-time
             * @description After this the device logs in through the bank again.
             */
            refreshExpiresAt: string;
        };
        AuthRefreshRequest: {
            refreshToken: string;
        };
        SessionResponse: {
            /** Format: uuid */
            sessionId: string;
            /** Format: uuid */
            accountId: string;
            platform: components["schemas"]["AuthPlatform"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            refreshExpiresAt: string;
        };
        /** @enum {string} */
        AuthPlatform: "ios" | "android";
        AdminSession: {
            accessToken: string;
            /** Format: date-time */
            expiresAt: string;
            role: components["schemas"]["ModeratorRole"];
        };
        /** @enum {string} */
        ModeratorRole: "moderator" | "admin" | "researcher";
        AdminAuthExchangeRequest: {
            code: string;
        };
        AdminWhoAmI: {
            role: components["schemas"]["ModeratorRole"];
            /** Format: date-time */
            expiresAt: string;
        };
        AccountDeletionRequest: {
            /**
             * @description Must be true: the person confirmed in the app.
             * @enum {boolean}
             */
            confirm: true;
        };
        AccountExport: {
            /** Format: date-time */
            exportedAt: string;
            account: {
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                state: "registered" | "active" | "paused" | "shadow_banned" | "suspended" | "banned" | "deleted";
                /** Format: date-time */
                registeredAt: string;
                birthYear: number | null;
                birthMonth: number | null;
                gender: components["schemas"]["Gender"];
                pond: components["schemas"]["PondSummary"];
            };
            preferences: components["schemas"]["PreferencesResponse"];
            consents: components["schemas"]["ConsentRecord"][];
            identity: {
                /** Format: date-time */
                firstSeenAt: string;
                /** Format: date-time */
                lastBankLoginAt: string | null;
                loginLevel: string | null;
                deletionCount: number;
            };
            sessions: {
                /** Format: uuid */
                sessionId: string;
                platform: components["schemas"]["AuthPlatform"];
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                lastUsedAt: string;
                /** Format: date-time */
                expiresAt: string;
            }[];
            profile: components["schemas"]["ProfileDocument"];
            photos: components["schemas"]["ExportedPhoto"][];
            photoAccessLog: {
                /** Format: uuid */
                photoId: string;
                variant: components["schemas"]["PhotoVariant"];
                /** Format: date-time */
                at: string;
            }[];
            research: components["schemas"]["ResearchExport"];
            gate: components["schemas"]["ExportedGate"];
        };
        /** @enum {string|null} */
        Gender: "woman" | "man" | "non_binary" | null;
        PondSummary: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            nameInessive: string;
            /** Format: uuid */
            parentId: string | null;
        } | null;
        PreferencesResponse: {
            seeks: components["schemas"]["Gender"][] | null;
            ageWindow: components["schemas"]["AgeWindow"];
        };
        AgeWindow: {
            min: number;
            max: number;
        } | null;
        ConsentRecord: {
            kind: components["schemas"]["ConsentKind"];
            version: string;
            /** @enum {string} */
            locale: "fi" | "sv" | "en";
            /** Format: date-time */
            givenAt: string;
            /** Format: date-time */
            withdrawnAt: string | null;
        };
        /** @enum {string} */
        ConsentKind: "terms" | "privacy" | "research";
        ProfileDocument: {
            displayName: string;
            bio: string | null;
            bioPreset: components["schemas"]["BioPreset"];
            fields: components["schemas"]["ProfileFields"];
            prompts: components["schemas"]["PromptAnswer"][];
            specialCategoryConsent: {
                version: string;
                /** Format: date-time */
                at: string;
            } | null;
            /** Format: date-time */
            updatedAt: string;
        } | null;
        /** @enum {string|null} */
        BioPreset: "lazy_nice_fellow" | "ask_me_instead" | "photos_speak" | null;
        ProfileFields: {
            /** @enum {string} */
            intent?: "long_term" | "casual" | "open_to_either";
            /** @enum {string} */
            identityLabel?: "agender" | "genderfluid" | "genderqueer" | "bigender" | "two_spirit" | "questioning" | "non_binary";
            /** @enum {string} */
            monogamy?: "monogamous" | "non_monogamous";
            /** @enum {string} */
            hasKids?: "no" | "yes_with_me" | "yes_not_with_me";
            /** @enum {string} */
            wantsKids?: "want" | "dont_want" | "not_sure";
            /** @enum {string} */
            smoking?: "never" | "sometimes" | "regularly" | "quitting";
            languages?: ("fi" | "sv" | "en" | "se" | "et" | "ru" | "uk" | "ar" | "so" | "fa" | "ku" | "zh" | "sq" | "vi" | "th" | "tr" | "es" | "de" | "fr" | "tl" | "pl" | "it" | "pt" | "hi" | "ne" | "bn" | "ur" | "ro" | "hu" | "ja" | "lt" | "lv" | "nl" | "ko" | "other")[];
            /** @enum {string} */
            education?: "peruskoulu" | "toinen_aste" | "amk" | "kandi" | "maisteri" | "tohtori";
            /** @enum {string} */
            drinking?: "never" | "rarely" | "socially" | "often";
            /** @enum {string} */
            drugsAttitude?: "not_my_thing" | "dont_mind" | "fine_with_it";
            hobbies?: ("hiking" | "cycling" | "running" | "skiing" | "swimming" | "sailing" | "foraging" | "fishing" | "climbing" | "gym" | "football" | "floorball" | "ice_hockey" | "yoga" | "dance" | "martial_arts" | "padel" | "photography" | "drawing" | "making_music" | "writing" | "crafts" | "theatre" | "cooking" | "baking" | "coffee" | "wine_and_beer" | "reading" | "cinema" | "museums" | "concerts" | "podcasts" | "board_games" | "video_games" | "chess" | "puzzles" | "gardening" | "sauna" | "cottage" | "diy" | "travelling" | "road_trips" | "learning_languages" | "dogs" | "cats" | "horses" | "birdwatching" | "programming" | "electronics" | "astronomy" | "volunteering" | "karaoke" | "pub_quiz" | "dinner_parties" | "meditation" | "winter_swimming" | "forest_walks" | "slow_mornings" | "other")[];
            height?: number;
            /** @enum {string} */
            exercise?: "never" | "sometimes" | "weekly" | "daily";
            pets?: ("dog" | "cat" | "other" | "none" | "allergic")[];
            /** @enum {string} */
            field?: "tech" | "engineering" | "business" | "arts" | "science" | "health" | "education" | "law" | "social" | "trades" | "service" | "other";
            hideFromField?: boolean;
            /** @enum {string} */
            occupation?: "student" | "tech" | "healthcare" | "education" | "business" | "arts_culture" | "science" | "trades_construction" | "service_hospitality" | "public_sector" | "transport" | "agriculture" | "media" | "law_finance" | "sports" | "entrepreneur" | "between_jobs" | "retired" | "other";
            occupationTitle?: string;
            politics?: ("kok" | "ps" | "sdp" | "kesk" | "vihr" | "vas" | "rkp" | "kd" | "liik" | "none_of_them" | "kahvipuolue")[];
            /** @enum {string} */
            religion?: "lutheran" | "orthodox" | "other_christian" | "muslim" | "jewish" | "buddhist" | "hindu" | "spiritual" | "agnostic" | "atheist" | "other";
            /** @enum {string} */
            zodiac?: "aries" | "taurus" | "gemini" | "cancer" | "leo" | "virgo" | "libra" | "scorpio" | "sagittarius" | "capricorn" | "aquarius" | "pisces" | "corgi";
        };
        PromptAnswer: {
            key: components["schemas"]["PromptKey"];
            answer: string;
        };
        /** @enum {string} */
        PromptKey: "sunday" | "proud_of" | "argue_about" | "unpopular_opinion" | "teach_me" | "first_date" | "never_again" | "overrated" | "hidden_talent" | "last_laugh" | "three_things" | "ask_me";
        ExportedPhoto: {
            id: components["schemas"]["PhotoId"];
            /** @description Placeholder the app paints before the thumb arrives (computed from the thumb). */
            blurhash: string;
            /** @description Of the full variant. */
            width: number;
            /** @description Of the full variant. */
            height: number;
            state: components["schemas"]["PhotoState"];
            /**
             * @description Set when state is rejected: the reason the owner is told.
             * @enum {string|null}
             */
            rejectionReason: "nudity" | "no_person" | "several_people" | "minor" | "violence" | "contact_details" | "other" | null;
            /** @description 0 is the main photo; the owner sets the order. */
            position: number;
            /** Format: date-time */
            createdAt: string;
            urls: components["schemas"]["SignedVariantUrls"];
            /** @description The moderation outcome; label names are not part of it. */
            review: {
                /** @enum {string} */
                decision: "approved" | "queued" | "rejected";
                reason: components["schemas"]["PhotoRejectionReason"];
                /** @description True when a person decided, false when the automatic check did. */
                decidedByStaff: boolean;
                /** Format: date-time */
                decidedAt: string | null;
            } | null;
        };
        /** Format: uuid */
        PhotoId: string;
        /** @enum {string} */
        PhotoState: "pending" | "approved" | "queued" | "rejected";
        /** @description Fifteen-minute URLs, one per variant. */
        SignedVariantUrls: {
            /** Format: uri */
            thumb: string;
            /** Format: uri */
            card: string;
            /** Format: uri */
            full: string;
        } | null;
        /** @enum {string|null} */
        PhotoRejectionReason: "nudity" | "no_person" | "several_people" | "minor" | "violence" | "contact_details" | "other" | null;
        /**
         * @description thumb: 200×200 for lists. card: 800×1067 when a profile is opened. full: 1600 px long edge, requested only from the zoom screen.
         * @enum {string}
         */
        PhotoVariant: "thumb" | "card" | "full";
        ResearchExport: {
            enrolled: boolean;
            /** Format: date-time */
            since: string | null;
            consentVersion: string | null;
            events: components["schemas"]["ResearchEventRecord"][];
        };
        ResearchEventRecord: {
            name: string;
            /** Format: date-time */
            at: string;
            consentVersion: string;
            pond: string | null;
            ageBand: string;
            snapshot: components["schemas"]["ResearchSnapshot"];
            props: {
                [key: string]: unknown;
            };
        };
        ResearchSnapshot: {
            gender: components["schemas"]["Gender"];
            fields: components["schemas"]["ResearchFields"];
        };
        ResearchFields: {
            /** @enum {string} */
            intent?: "long_term" | "casual" | "open_to_either";
            /** @enum {string} */
            identityLabel?: "agender" | "genderfluid" | "genderqueer" | "bigender" | "two_spirit" | "questioning" | "non_binary";
            /** @enum {string} */
            monogamy?: "monogamous" | "non_monogamous";
            /** @enum {string} */
            hasKids?: "no" | "yes_with_me" | "yes_not_with_me";
            /** @enum {string} */
            wantsKids?: "want" | "dont_want" | "not_sure";
            /** @enum {string} */
            smoking?: "never" | "sometimes" | "regularly" | "quitting";
            languages?: ("fi" | "sv" | "en" | "se" | "et" | "ru" | "uk" | "ar" | "so" | "fa" | "ku" | "zh" | "sq" | "vi" | "th" | "tr" | "es" | "de" | "fr" | "tl" | "pl" | "it" | "pt" | "hi" | "ne" | "bn" | "ur" | "ro" | "hu" | "ja" | "lt" | "lv" | "nl" | "ko" | "other")[];
            /** @enum {string} */
            education?: "peruskoulu" | "toinen_aste" | "amk" | "kandi" | "maisteri" | "tohtori";
            /** @enum {string} */
            drinking?: "never" | "rarely" | "socially" | "often";
            /** @enum {string} */
            drugsAttitude?: "not_my_thing" | "dont_mind" | "fine_with_it";
            hobbies?: ("hiking" | "cycling" | "running" | "skiing" | "swimming" | "sailing" | "foraging" | "fishing" | "climbing" | "gym" | "football" | "floorball" | "ice_hockey" | "yoga" | "dance" | "martial_arts" | "padel" | "photography" | "drawing" | "making_music" | "writing" | "crafts" | "theatre" | "cooking" | "baking" | "coffee" | "wine_and_beer" | "reading" | "cinema" | "museums" | "concerts" | "podcasts" | "board_games" | "video_games" | "chess" | "puzzles" | "gardening" | "sauna" | "cottage" | "diy" | "travelling" | "road_trips" | "learning_languages" | "dogs" | "cats" | "horses" | "birdwatching" | "programming" | "electronics" | "astronomy" | "volunteering" | "karaoke" | "pub_quiz" | "dinner_parties" | "meditation" | "winter_swimming" | "forest_walks" | "slow_mornings" | "other")[];
            /** @enum {string} */
            exercise?: "never" | "sometimes" | "weekly" | "daily";
            pets?: ("dog" | "cat" | "other" | "none" | "allergic")[];
            /** @enum {string} */
            field?: "tech" | "engineering" | "business" | "arts" | "science" | "health" | "education" | "law" | "social" | "trades" | "service" | "other";
            /** @enum {string} */
            occupation?: "student" | "tech" | "healthcare" | "education" | "business" | "arts_culture" | "science" | "trades_construction" | "service_hospitality" | "public_sector" | "transport" | "agriculture" | "media" | "law_finance" | "sports" | "entrepreneur" | "between_jobs" | "retired" | "other";
            /** @enum {string} */
            zodiac?: "aries" | "taurus" | "gemini" | "cancer" | "leo" | "virgo" | "libra" | "scorpio" | "sagittarius" | "capricorn" | "aquarius" | "pisces" | "corgi";
        };
        ExportedGate: {
            /** Format: uuid */
            pondId: string;
            /** Format: date-time */
            admittedAt: string | null;
            placeSaid: number | null;
            poolSaid: number;
            /** Format: date-time */
            openedAt: string | null;
            /** Format: date-time */
            countedAt: string | null;
        } | null;
        PhotoList: {
            photos: components["schemas"]["Photo"][];
            /** @description matching_config max_photos. */
            maxPhotos: number;
        };
        Photo: {
            id: components["schemas"]["PhotoId"];
            /** @description Placeholder the app paints before the thumb arrives (computed from the thumb). */
            blurhash: string;
            /** @description Of the full variant. */
            width: number;
            /** @description Of the full variant. */
            height: number;
            state: components["schemas"]["PhotoState"];
            /**
             * @description Set when state is rejected: the reason the owner is told.
             * @enum {string|null}
             */
            rejectionReason: "nudity" | "no_person" | "several_people" | "minor" | "violence" | "contact_details" | "other" | null;
            /** @description 0 is the main photo; the owner sets the order. */
            position: number;
            /** Format: date-time */
            createdAt: string;
        };
        PhotoUploadRequest: {
            /**
             * Format: binary
             * @description The picture, pre-resized to 1600 px by the app; JPEG, PNG or WebP.
             */
            photo: string;
        };
        PhotoOrderRequest: {
            order: components["schemas"]["PhotoId"][];
        };
        PhotoUrlResponse: {
            /** Format: uri */
            url: string;
            variant: components["schemas"]["PhotoVariant"];
            /** Format: date-time */
            expiresAt: string;
        };
        PhotoReviewQueue: {
            items: components["schemas"]["PhotoReviewItem"][];
            total: number;
        };
        PhotoReviewItem: {
            photoId: components["schemas"]["PhotoId"];
            /** Format: uuid */
            accountId: string;
            state: components["schemas"]["PhotoState"];
            blurhash: string;
            width: number;
            height: number;
            /** Format: date-time */
            uploadedAt: string;
            /** Format: date-time */
            checkedAt: string | null;
            labels: components["schemas"]["ModerationLabel"][];
            faces: number;
            flagged: string[];
        };
        ModerationLabel: {
            name: string;
            parentName: string;
            confidence: number;
        };
        PhotoDecisionResponse: {
            photoId: components["schemas"]["PhotoId"];
            state: components["schemas"]["PhotoState"];
            rejectionReason: components["schemas"]["PhotoRejectionReason"];
        };
        PhotoDecisionRequest: {
            /** @enum {string} */
            decision: "approve";
        } | {
            /** @enum {string} */
            decision: "reject";
            reason: components["schemas"]["PhotoRejectionReason"];
        };
        ProfileResponse: {
            profile: components["schemas"]["ProfileDocument"];
            completeness: components["schemas"]["Completeness"];
        };
        Completeness: {
            complete: boolean;
            missing: components["schemas"]["CompletenessItem"][];
        };
        /** @enum {string} */
        CompletenessItem: "display_name" | "photos" | "bio_or_prompts" | "seeks" | "age_window";
        ProfileUpdate: {
            displayName: string;
            bio: string | null;
            bioPreset: components["schemas"]["BioPreset"];
            fields: components["schemas"]["ProfileFields"];
            prompts: components["schemas"]["PromptAnswer"][];
            specialCategoryConsent: {
                version: string;
            } | null;
        };
        CardPreviewResponse: {
            card: components["schemas"]["ProfileCard"];
            completeness: components["schemas"]["Completeness"];
        };
        ProfileCard: {
            /** Format: uuid */
            accountId: string;
            displayName: string;
            age: {
                years: number;
                /** @enum {boolean} */
                verifiedByBank: true;
            };
            pond: components["schemas"]["PondSummary"];
            photos: components["schemas"]["CardPhoto"][];
            fields: components["schemas"]["ProfileFields"];
            bio: string | null;
            bioPreset: components["schemas"]["BioPreset"];
            prompts: components["schemas"]["PromptAnswer"][];
        } | null;
        CardPhoto: {
            id: components["schemas"]["PhotoId"];
            blurhash: string;
            width: number;
            height: number;
        };
        OnboardingStatus: {
            /** @enum {string} */
            state: "registered" | "active" | "paused" | "shadow_banned" | "suspended" | "banned" | "deleted";
            gender: components["schemas"]["Gender"];
            pond: components["schemas"]["PondSummary"];
            preferences: components["schemas"]["PreferencesResponse"];
            consents: {
                terms: string | null;
                privacy: string | null;
                research: {
                    version: string;
                    /** Format: date-time */
                    givenAt: string;
                } | null;
            };
            currentVersions: components["schemas"]["ConsentVersions"];
            missing: components["schemas"]["OnboardingStep"][];
            complete: boolean;
        };
        /** @description The consent_version of the current wording per kind. */
        ConsentVersions: {
            terms: string;
            privacy: string;
            research: string;
        };
        /** @enum {string} */
        OnboardingStep: "gender" | "seeks" | "age_window" | "pond" | "terms" | "privacy";
        GenderUpdate: {
            gender: components["schemas"]["Gender"];
        };
        ConsentsResponse: {
            consents: components["schemas"]["ConsentRecord"][];
            currentVersions: components["schemas"]["ConsentVersions"];
        };
        ConsentRequest: {
            kind: components["schemas"]["ConsentKind"];
            version: string;
            /** @enum {string} */
            locale: "fi" | "sv" | "en";
        };
        GateResponse: {
            state: components["schemas"]["GateState"];
            within: number | null;
            needed: number | null;
            step: number;
        };
        /** @enum {string} */
        GateState: "incomplete" | "pending" | "waiting" | "closed" | "open";
        WaitlistResponse: {
            k: number;
            ponds: components["schemas"]["WaitlistPond"][];
        };
        WaitlistPond: {
            pond: components["schemas"]["PondSummary"];
            /** Format: date */
            day: string | null;
            verified: number | null;
            split: components["schemas"]["WaitlistSplit"];
            finishing: number | null;
        };
        WaitlistSplit: {
            woman: number;
            man: number;
            nonBinary: number;
        } | null;
        PondList: {
            ponds: components["schemas"]["PondSummary"][];
        };
        PondChoice: {
            /** Format: uuid */
            pondId: string;
        };
        PreferencesUpdate: {
            seeks: components["schemas"]["Gender"][];
            ageWindow: components["schemas"]["AgeWindow"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
