import { checkCharacter } from "@kuutti/tunnistus-oidc/hetu";
import { assertArtificial, type DemoPersona, MOCK_BANK_ACR, MOCK_BANK_AMR } from "./personas.ts";

/**
 * The login page of the mock bank (#73, ADR-014): one button per persona and,
 * below them, the form for anybody else. It is the page
 * navikt/mock-oauth2-server serves at its authorize endpoint
 * (`loginPagePath`); a button posts what the server's own form would post, a
 * `username` and the `claims` for the ID token.
 *
 * The page computes a persona's code when the button is pressed, because some
 * personas are born relative to today. Its script says again, in a dozen
 * lines, what `personaClaims` says; a test runs the page's script against
 * that function for every persona on a range of days, so the two cannot part.
 *
 * Generated into services/mock-idp/login.html by `pnpm demo:bank`; a test
 * fails when the file and this module disagree.
 */

const GROUPS: ReadonlyArray<{ group: DemoPersona["group"]; title: string; lead: string }> = [
  {
    group: "walkthrough",
    title: "Newcomers",
    lead: "Never seen by Kuutti before the first login.",
  },
  {
    group: "history",
    title: "People with a history",
    lead: "The same identity on every day. What Kuutti holds about them is given by pnpm demo:reset; before it has run they are newcomers too.",
  },
  {
    group: "ages",
    title: "Ages",
    lead: "Born relative to today, so the age holds whenever this runs and the identity changes as the months pass.",
  },
];

const escapeHtml = (text: string): string =>
  text.replace(/[&<>"']/g, (c) => `&#${c.charCodeAt(0)};`);

/** `<` never appears in the script's data, so no persona's text can close the script element. */
const scriptJson = (value: unknown): string => JSON.stringify(value).replace(/</g, "\\u003c");

/** The claims the form for anybody else starts with: an artificial person, to be edited. */
const SOMEBODY = {
  "urn:oid:1.2.246.21": `010190-999${checkCharacter("010190", "999")}`,
  "urn:oid:1.3.6.1.5.5.7.9.1": "1990-01-01",
  "urn:oid:2.5.4.4": "Henkilö",
  "urn:oid:1.2.246.575.1.14": "Testi",
  "urn:oid:2.16.840.1.113730.3.1.241": "Testi Henkilö",
  acr: MOCK_BANK_ACR,
  amr: [MOCK_BANK_AMR],
};

export function renderBankPage(personas: readonly DemoPersona[]): string {
  // The page computes the codes itself, so the range is held here, before anything is written.
  for (const persona of personas) assertArtificial(persona);
  const sections = GROUPS.map(({ group, title, lead }) => {
    const buttons = personas
      .filter((p) => p.group === group)
      .map(
        (p) => `        <li>
          <button type="button" data-persona="${escapeHtml(p.key)}">
            <span class="name">${escapeHtml(`${p.given} ${p.family}`)}</span>
            <span class="note">${escapeHtml(p.note)}</span>
          </button>
        </li>`,
      )
      .join("\n");
    return `    <section aria-labelledby="group-${group}">
      <h2 id="group-${group}">${escapeHtml(title)}</h2>
      <p class="lead">${escapeHtml(lead)}</p>
      <ul>
${buttons}
      </ul>
    </section>`;
  }).join("\n");

  const data = personas.map(({ key, given, family, born, individual }) => ({
    key,
    given,
    family,
    born,
    individual,
  }));

  return `<!doctype html>
<!-- Generated by \`pnpm demo:bank\` from packages/db/src/seed; do not edit by hand. -->
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="robots" content="noindex" />
    <title>Mock bank · Kuutti local development</title>
    <style>
      :root { color-scheme: light dark; --ink: #0f172a; --soft: #475569; --line: #94a3b8; --page: #f8fafc; --card: #ffffff; --mark: #1d4ed8; }
      @media (prefers-color-scheme: dark) {
        :root { --ink: #f1f5f9; --soft: #cbd5e1; --line: #64748b; --page: #0f172a; --card: #1e293b; --mark: #93c5fd; }
      }
      * { box-sizing: border-box; }
      body { margin: 0; padding: 24px 16px 48px; background: var(--page); color: var(--ink); font: 16px/1.5 system-ui, sans-serif; }
      main { max-width: 640px; margin: 0 auto; }
      h1 { font-size: 1.5rem; margin: 0 0 4px; }
      h2 { font-size: 1.125rem; margin: 32px 0 4px; }
      .lead, .warning { color: var(--soft); margin: 0 0 12px; }
      .warning { border-left: 4px solid var(--mark); padding-left: 12px; }
      ul { list-style: none; margin: 0; padding: 0; display: grid; gap: 8px; }
      button { font: inherit; color: inherit; cursor: pointer; border: 1px solid var(--line); border-radius: 8px; background: var(--card); }
      button[data-persona] { display: block; width: 100%; min-height: 56px; padding: 10px 14px; text-align: left; }
      button:focus-visible, textarea:focus-visible, input:focus-visible { outline: 3px solid var(--mark); outline-offset: 2px; }
      .name { display: block; font-weight: 600; }
      .note { display: block; color: var(--soft); font-size: 0.9375rem; }
      label { display: block; font-weight: 600; margin: 12px 0 4px; }
      input, textarea { font: inherit; color: inherit; width: 100%; padding: 10px; border: 1px solid var(--line); border-radius: 8px; background: var(--card); }
      textarea { font-family: ui-monospace, monospace; font-size: 0.875rem; min-height: 14rem; }
      button[type="submit"] { min-height: 48px; padding: 10px 20px; margin-top: 12px; font-weight: 600; }
    </style>
  </head>
  <body>
    <main>
      <h1>Mock bank</h1>
      <p class="warning">
        This stands in for bank identification on a developer's machine. Nobody here is a person:
        every code on this page is artificial.
      </p>
${sections}
      <section aria-labelledby="group-somebody">
        <h2 id="group-somebody">Somebody else</h2>
        <p class="lead">
          The claims go into the ID token as they are. Use generated codes only, never a person's.
        </p>
        <form method="post" id="login">
          <label for="username">Name at the bank</label>
          <input id="username" name="username" value="testi" autocomplete="off" required />
          <label for="claims">Claims</label>
          <textarea id="claims" name="claims" spellcheck="false">${escapeHtml(JSON.stringify(SOMEBODY, null, 2))}</textarea>
          <button type="submit">Identify</button>
        </form>
      </section>
    </main>
    <script>
      const PERSONAS = ${scriptJson(data)};
      const ACR = ${scriptJson(MOCK_BANK_ACR)};
      const AMR = ${scriptJson(MOCK_BANK_AMR)};
      const CHECK = "0123456789ABCDEFHJKLMNPRSTUVWXY";
      const two = (n) => String(n).padStart(2, "0");

      // The same rules as personaBirth and personaClaims in packages/db/src/seed/personas.ts.
      function birthOf(persona, at) {
        if ("year" in persona.born) return persona.born;
        const months =
          (at.getUTCFullYear() - persona.born.yearsAgo) * 12 + at.getUTCMonth() - persona.born.monthsAgo;
        return { year: Math.floor(months / 12), month: (months % 12) + 1, day: 1 };
      }

      function claimsOf(persona, at) {
        const born = birthOf(persona, at);
        const sign = born.year < 1900 ? "+" : born.year < 2000 ? "-" : "A";
        const ddmmyy = \`\${two(born.day)}\${two(born.month)}\${two(born.year % 100)}\`;
        const individual = String(persona.individual);
        const check = CHECK[Number.parseInt(\`\${ddmmyy}\${individual}\`, 10) % 31];
        return {
          "urn:oid:1.2.246.21": \`\${ddmmyy}\${sign}\${individual}\${check}\`,
          "urn:oid:1.3.6.1.5.5.7.9.1": \`\${born.year}-\${two(born.month)}-\${two(born.day)}\`,
          "urn:oid:2.5.4.4": persona.family,
          "urn:oid:1.2.246.575.1.14": persona.given,
          "urn:oid:2.16.840.1.113730.3.1.241": \`\${persona.given} \${persona.family}\`,
          acr: ACR,
          amr: [AMR],
        };
      }

      document.addEventListener("click", (event) => {
        const button = event.target.closest("button[data-persona]");
        if (!button) return;
        const persona = PERSONAS.find((p) => p.key === button.dataset.persona);
        const form = document.getElementById("login");
        form.elements.username.value = persona.key;
        form.elements.claims.value = JSON.stringify(claimsOf(persona, new Date()));
        form.submit();
      });
    </script>
  </body>
</html>
`;
}
