/**
 * What the synthetic people are called and what they say (#73). Every line
 * was written for this file: nothing is copied from a profile, a person or a
 * site. Small on purpose, and hand-made rather than generated by a library:
 * a hundred lines that read like a pond in Espoo are better on camera than
 * ten thousand that read like nowhere.
 *
 * Everything here is text a person could have typed, so everything passes the
 * plain-text rule of the profile (no address, no number, no handle); a test
 * in the API runs every line through it.
 */

export type Language = "fi" | "sv" | "en";

/** Given names only: a display name is what a person chooses to be called. */
export const NAMES = {
  woman: [
    "Aino",
    "Helmi",
    "Sofia",
    "Ella",
    "Venla",
    "Iida",
    "Enni",
    "Siiri",
    "Noora",
    "Laura",
    "Riikka",
    "Kaisa",
    "Maija",
    "Elina",
    "Linnea",
    "Ronja",
    "Saga",
    "Elsa",
    "Alva",
    "Åsa",
    "Päivi",
    "Юлия",
  ],
  man: [
    "Eetu",
    "Onni",
    "Leo",
    "Elias",
    "Väinö",
    "Eino",
    "Niilo",
    "Aleksi",
    "Juho",
    "Ville",
    "Mikko",
    "Antti",
    "Tuomas",
    "Janne",
    "Otto",
    "Axel",
    "Emil",
    "Anton",
    "Oskar",
    "Håkan",
    "Yrjö",
    "Ali",
  ],
  non_binary: [
    "Kuu",
    "Ruska",
    "Sumu",
    "Tuisku",
    "Lumi",
    "Noa",
    "Robin",
    "Alex",
    "Sam",
    "Kaarna",
    "Routa",
    "Myrsky",
    "Pilvi",
    "Charlie",
  ],
} as const;

/**
 * Job titles in the person's words and language: short, and never an
 * employer's name, so no organisation that exists is given members who do
 * not (ADR-019 §5).
 */
export const OCCUPATION_TITLES: Readonly<Record<Language, readonly string[]>> = {
  fi: [
    "arkkitehti",
    "sairaanhoitaja",
    "luokanopettaja",
    "ohjelmistokehittäjä",
    "kirvesmies",
    "tutkija",
    "kokki",
    "bussinkuljettaja",
    "graafikko",
    "fysioterapeutti",
  ],
  sv: [
    "sjukskötare",
    "klasslärare",
    "snickare",
    "forskare",
    "kock",
    "bibliotekarie",
    "ingenjör",
    "trädgårdsmästare",
  ],
  en: [
    "data analyst",
    "nurse",
    "software developer",
    "barista",
    "doctoral researcher",
    "project manager",
    "electrician",
    "translator",
    "UX designer",
    "chef",
  ],
};

/** Bios. The first of each language are long enough to count for completeness, the last ones are not. */
export const BIOS: Readonly<Record<Language, readonly string[]>> = {
  fi: [
    "Aamuihminen vain kesällä. Talvella minut löytää saunan lauteilta tai uimahallin hitaimmalta radalta. Etsin seuraa, jonka kanssa hiljaisuus ei tunnu oudolta.",
    "Leivon enemmän kuin ehdin syödä, joten naapurit tuntevat minut korvapuusteista. Haaveilen mökistä, jossa on huono nettiyhteys ja hyvä laituri.",
    "Insinööri päivisin, kuorolaulaja iltaisin. Kysy minulta Helsingin parhaasta lounaskeitosta, minulla on siitä taulukko ja vahva mielipide.",
    "Muutin tänne opiskelemaan ja jäin, koska meri. Pyöräilen töihin säällä kuin säällä ja valitan siitä vain vähän.",
    "Pidän pitkistä kävelyistä, lyhyistä kokouksista ja ihmisistä, jotka nauravat omille vitseilleen. Koirani päättää viikonlopun aikataulun.",
    "Sienestän, neulon ja väittelen mielelläni siitä, kuuluuko ruisleivän päälle voita. Kuuluu. Etsin jotain, mikä kestää arkea.",
    "Luen kolmea kirjaa yhtä aikaa enkä saa yhtäkään loppuun ennen kesälomaa. Hyvä kahvi ja huono elokuva ovat täydellinen sunnuntai.",
    "Kiipeilen sisällä, koska ulkona on liian usein märkää. Osaan korjata pyörän, en osaa tanssia, harjoittelen kumpaakin.",
    "Uusi kaupungissa.",
    "Kerron lisää kasvotusten.",
  ],
  sv: [
    "Uppvuxen vid havet och blir rastlös om jag inte ser vatten på en vecka. Jag seglar på sommaren och lagar alldeles för stora grytor på vintern.",
    "Lärare på dagarna, amatörbagare på kvällarna. Jag letar efter någon som tycker att en promenad i regn också räknas som en dejt.",
    "Jag sjunger i kör, cyklar till jobbet och har starka åsikter om kanelbullar. Berätta gärna vad du läser just nu.",
    "Flyttade hit för studierna och blev kvar för skärgården. Bäst trivs jag i bastun efter ett kallt dopp.",
    "Nyfiken, lite envis och alltid hungrig. Söker någon att dela vardagen med, inte bara helgerna.",
    "Ny i stan.",
  ],
  en: [
    "Moved here for a degree and stayed for the sea. I cycle in all weather and complain about it only a little. Looking for someone to be quiet with.",
    "Engineer by day, choir singer by night. I keep a spreadsheet of the best soup lunches in town and I will defend it.",
    "I bake more than I can eat, so my neighbours know me by my cinnamon buns. Dreaming of a cabin with a bad connection and a good pier.",
    "Learning Finnish one grocery label at a time. I like long walks, short meetings and people who laugh at their own jokes.",
    "Indoor climber, outdoor complainer. I can fix a bicycle, I cannot dance, and I am working on both.",
    "Three books on the go and none of them finished before the summer. Good coffee and a bad film is a perfect Sunday.",
    "New in town.",
  ],
};

/** Answers to the prompts of the profile, by prompt key. */
export const PROMPT_ANSWERS: Readonly<
  Record<string, Readonly<Record<Language, readonly string[]>>>
> = {
  sunday: {
    fi: ["Sauna, sitten pitkä aamiainen.", "Kirpputori ja pannukahvit."],
    sv: ["Bastu och sedan en lång frukost."],
    en: ["Sauna, then a long breakfast.", "A flea market and too much coffee."],
  },
  proud_of: {
    fi: ["Opin uimaan aikuisena.", "Hapanjuureni on elänyt kuusi vuotta."],
    sv: ["Jag lärde mig simma som vuxen."],
    en: ["I learned to swim as an adult.", "My sourdough starter is six years old."],
  },
  argue_about: {
    fi: ["Kuuluuko ananas pizzaan. Kuuluu.", "Mikä on oikea tapa ripustaa pyykit."],
    sv: ["Om ananas hör hemma på pizza. Det gör den."],
    en: ["Whether pineapple belongs on pizza. It does.", "The right way to load a dishwasher."],
  },
  unpopular_opinion: {
    fi: ["Marraskuu on vuoden paras kuukausi.", "Salmiakki on yliarvostettua."],
    sv: ["November är årets bästa månad."],
    en: ["November is the best month of the year.", "Salty liquorice is overrated."],
  },
  teach_me: {
    fi: ["Opeta minut tekemään karjalanpiirakoita.", "Miten solmitaan kunnon merimiessolmu."],
    sv: ["Lär mig att segla utan att bli sjösjuk."],
    en: ["How to make Karelian pies.", "How to parallel park without an audience."],
  },
  first_date: {
    fi: ["Kävely meren rannassa ja korvapuusti.", "Näyttely, josta kumpikaan ei tiedä mitään."],
    sv: ["En promenad vid havet och en kanelbulle."],
    en: [
      "A walk by the sea and a cinnamon bun.",
      "An exhibition neither of us knows anything about.",
    ],
  },
  never_again: {
    fi: ["Telttaretki ilman makuualustaa.", "Juhannus ilman hyttysmyrkkyä."],
    sv: ["Tälta utan liggunderlag."],
    en: ["Camping without a sleeping mat.", "Midsummer without mosquito repellent."],
  },
  overrated: {
    fi: ["Aikaiset aamut.", "Avokonttorit."],
    sv: ["Tidiga morgnar."],
    en: ["Early mornings.", "Open-plan offices."],
  },
  hidden_talent: {
    fi: ["Tunnistan linnut äänestä.", "Osaan vislata kahdella äänellä."],
    sv: ["Jag känner igen fåglar på sången."],
    en: ["I can tell birds by their song.", "I can fold a fitted sheet."],
  },
  last_laugh: {
    fi: ["Koirani yritti varastaa naapurin grillimakkaran.", "Oma vitsini, valitettavasti."],
    sv: ["Min hund försökte stjäla grannens korv."],
    en: ["My dog tried to steal the neighbour's sausage.", "My own joke, unfortunately."],
  },
  three_things: {
    fi: ["Kahvi, villasukat ja hyvä kirja.", "Meri, metsä ja hiljaisuus."],
    sv: ["Kaffe, yllesockor och en bra bok."],
    en: ["Coffee, wool socks and a good book.", "The sea, the forest and some quiet."],
  },
  ask_me: {
    fi: ["Kysy, miksi minulla on kolme kanoottia.", "Kysy parhaasta sienipaikastani. En kerro."],
    sv: ["Fråga varför jag har tre kanoter."],
    en: ["Ask me why I own three canoes.", "Ask about my best mushroom spot. I will not tell."],
  },
};

/** Every line a synthetic person can say, for the test that reads them all. */
export function everyText(): string[] {
  return [
    ...Object.values(NAMES).flat(),
    ...Object.values(OCCUPATION_TITLES).flat(),
    ...Object.values(BIOS).flat(),
    ...Object.values(PROMPT_ANSWERS).flatMap((byLanguage) => Object.values(byLanguage).flat()),
  ];
}
